#端口
server:
  port: 8888

# 安全配置
security:
  user:
    name: admin
    password: 123456
  basic:
    enabled: true

# eureka 配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:${server.port}/eureka/
  instance:
    #使用IP
    prefer-ip-address: false
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
    #自定义 instance id 默认是 ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    #instance-id:



spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aillamsun/devX-cloud
          search-paths: devx-config-repo
          username:
          password:
  # rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

