eureka:
    instance:
      hostname: localhost
      statusPageUrlPath: /info
      healthCheckUrlPath: /health
      #docker 部署开启
      prefer-ip-address: false
      #ip-address: 127.0.0.1
      # 续约更新时间间隔（默认30秒）
      lease-renewal-interval-in-seconds: 10
      # 续约到期时间（默认90秒）
      lease-expiration-duration-in-seconds: 30
       # 自定义instance-id
      instance-id: ${spring.application.name}:${server.port}:${random.value}
    client:
      service-url:
        # defaultZone: http://localhost:8761/eureka/
        # docker 部署开启
        defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:8671/eureka/
      healthcheck:
        enabled: true
      eurekaServiceUrlPollIntervalSeconds: 60
      enabled: true


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000


# 安全配置
security:
  user:
    name: admin
    password: 123456
  basic:
    enabled: true


#actuator暴露的health接口权限是由两个配置:
#actuator是否需要安全保证
management:
  security:
    enabled: false
#actuator的health接口是否需要安全保证
endpoints:
  health:
    sensitive: false



spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  sleuth:
    sampler:
      percentage: 1
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"



authserver:
    hostname: auth
    port: 5000
    contextPath: /uaa

security:
  oauth2:
    resource:
      user-info-uri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}/current