#端口
server:
  port: 8040

logging:
  level:
    org.springframework.cloud.netflix.zuul.filters.post.SendErrorFilter: error

turbine:
  stream:
    port: 8041

spring:
  boot:
      admin:
        routes:
          endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
        turbine:
          clusters: default
          location: turbine
#          location: http://localhost:${turbine.stream.port}
