#端口
server:
  port: 8040

boot:
  admin:
    routes:
      endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
    turbine:
      clusters: default
      location: http://localhost:${turbine.stream.port}


logging:
  level:
    org.springframework.cloud.netflix.zuul.filters.post.SendErrorFilter: error



turbine:
  stream:
    port: 8041

# 安全配置
security:
  user:
    name: admin
    password: 123456
    role: USER
  basic:
    enabled: true




spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest