server:
  port: 8044
##redis 集群环境配置
##redis cluster
#spring.redis.cluster.nodes=127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003
#spring.redis.cluster.commandTimeout=5000

##redis 单点环境配置
#redis
#redis主机地址
spring:
  thymeleaf:
    prefix: classpath:/html/
    suffix: .html
  redis:
    #redis主机端口
    host: localhost
    port: 6379
#    password: Chinawiservqz#
    timeout: 0
    pool:
      max-active: 10
      max-wait: 1
      max-idle: 5
      min-idle: 0


management:
  security:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000


# 安全配置
security:
  user:
    name: admin
    password: 123456
  basic:
    enabled: true

eureka:
    instance:
      hostname: localhost
      statusPageUrlPath: /info
      healthCheckUrlPath: /health
      #docker 部署开启
      prefer-ip-address: false
       #ip-address: 127.0.0.1
      # 续约更新时间间隔（默认30秒）
      lease-renewal-interval-in-seconds: 10
      # 续约到期时间（默认90秒）
      lease-expiration-duration-in-seconds: 30
    client:
      service-url:
        # defaultZone: http://localhost:8761/eureka/
        # docker 部署开启
        defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:8671/eureka/
      healthcheck:
        enabled: true
      eurekaServiceUrlPollIntervalSeconds: 60

endpoints:
  health:
    sensitive: false


#业务模块与TxManager之间通讯的最大等待时间（单位：秒）
transaction_netty_delay_time: 3
#业务模块与TxManager之间通讯的心跳时间（单位：秒）
transaction_netty_heart_time:  15
#存储到redis下的数据最大保存时间（单位：秒）
redis_save_max_time: 30
#socket server Socket对外服务端口
socket.port: 9999
# 最大socket连接数
socket.max.connection: 100
