server:
  port: 8090
  context-path:

  tomcat:
    uri-encoding: UTF-8
    max-threads: 800

# 是否显示异常信息
show-exception: true


log.path: /Users/sungang/Documents/logs/devx-user
log.level: INFO
#日志最多保留天数
log.maxHistory: 1
#会检查终端是否支持ANSI，是的话就采用彩色输出


########################################################
### Mybatis Setting
########################################################
#mybatis
mybatis:
  type-aliases-package: com.devx.model
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
#mapper
#mappers 多个接口时逗号隔开
mapper:
  mappers: com.devx.core.dao.mybatis.BaseMapper
  not-empty: false
  identity: MYSQL
  before: true
#pagehelper
pagehelper:
  helperDialect: MYSQL
  reasonable: true
  supportMethodsArguments: true
  params=count: countSql


# 数据库访问配置
# 主数据源，默认的
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/devx-cloud?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    #配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000

    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: wall,stat
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true