#端口
server:
  port: 8888

# 安全配置
security:
  user:
    name: admin
    password: 123456
  basic:
    enabled: true

# eureka 配置
eureka:
  client:
    service-url:
      # defaultZone: http://localhost:8761/eureka/
      # docker 部署开启
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:8671/eureka/
    healthcheck:
      enabled: true
    eurekaServiceUrlPollIntervalSeconds: 60
  instance:
    hostname: localhost
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    #docker 部署开启
    prefer-ip-address: false
     #ip-address: 127.0.0.1
    # 续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 10
    # 续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 30

#    metadata-map:
#      user.name: ${security.user.name}
#      user.password: ${security.user.password}
    #自定义 instance id 默认是 ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    #instance-id:


spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aillamsun/devX-cloud
          search-paths: devx-config-repo
#          username:
#          password:
  # rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

